version: '3.1'
services:
  spring-postgre-docker-1:
    image: shaiful365/spring-postgre-docker
    container_name: spring-postgre-docker-1
    ports:
      - "9050:8080"
    depends_on:
      - PostgreSQL
    networks:
      spring-postgre-docker-network-1:

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/branch
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  PostgreSQL:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=branch
    networks:
      spring-postgre-docker-network-1:

networks:
  spring-postgre-docker-network-1:
    driver: bridge


# docker-compose-docker-api-and-docker-db.yml