version: '3.1'
services:

  spring-postgre-docker-1:
    image: shaiful365/spring-postgre-docker
    container_name: spring-postgre-docker-1
    ports:
      - "9050:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.10.0.1:5432/branch_local
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - spring-postgre-docker-network-3

networks:
  spring-postgre-docker-network-3:
    driver: bridge


# docker-compose  -f docker-compose-docker-api-and-local-db.yml up
# docker-compose  -f docker-compose-docker-api-and-local-db.yml down